"""Add image_url to articles table

Revision ID: 17e63d07e08d
Revises: 2feb4b948200
Create Date: 2025-09-11 22:20:48.532802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e63d07e08d'
down_revision: Union[str, None] = '2feb4b948200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add image_url column to existing articles table
    op.add_column('articles', sa.Column('image_url', sa.String(length=1024), nullable=True), schema='articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove image_url column from articles table
    op.drop_column('articles', 'image_url', schema='articles')
    # ### end Alembic commands ###
