"""Add related_statistics to enriched_articles

Revision ID: ab666d65e925
Revises: acf36018cb31
Create Date: 2025-09-09 00:10:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = 'ab666d65e925'
down_revision: Union[str, None] = 'acf36018cb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 목표 작업: 'enriched_articles' 테이블에 'related_statistics' 컬럼 추가
    op.add_column(
        'enriched_articles',
        sa.Column('related_statistics', JSONB(), nullable=True),
        schema='articles'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 'upgrade'의 반대 작업: 'related_statistics' 컬럼 삭제
    op.drop_column(
        'enriched_articles',
        'related_statistics',
        schema='articles'
    )

    # ### end Alembic commands ###
