"""Initial schemas

Revision ID: acf36018cb31
Revises: 
Create Date: 2025-09-08 23:38:21.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.enums import ArticleStatus

from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = 'acf36018cb31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(sa.schema.CreateSchema('articles', if_not_exists=True))
    op.execute(sa.schema.CreateSchema('statistics', if_not_exists=True))

    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='articlestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='articles'
    )
    op.create_index(op.f('ix_articles_articles_category'), 'articles', ['category'], unique=False, schema='articles')
    op.create_index(op.f('ix_articles_articles_url'), 'articles', ['url'], unique=True, schema='articles')
    op.create_table('indicators',
    sa.Column('indicator_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stat_code', sa.String(length=20), nullable=True),
    sa.Column('item_code1', sa.String(length=20), nullable=True),
    sa.Column('item_code2', sa.String(length=20), nullable=True),
    sa.Column('item_code3', sa.String(length=20), nullable=True),
    sa.Column('item_code4', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('indicator_id'),
    schema='statistics'
    )
    op.create_table('article_contents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id'),
    schema='articles'
    )
    op.create_table('enriched_articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('background', JSONB(), nullable=True),
    sa.Column('keywords', JSONB(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id'),
    schema='articles'
    )
    op.create_table('observations',
    sa.Column('indicator_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['statistics.indicators.indicator_id'], ),
    sa.PrimaryKeyConstraint('indicator_id', 'date'),
    schema='statistics'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations', schema='statistics')
    op.drop_table('enriched_articles', schema='articles')
    op.drop_table('article_contents', schema='articles')
    op.drop_table('indicators', schema='statistics')
    op.drop_index(op.f('ix_articles_articles_url'), table_name='articles', schema='articles')
    op.drop_index(op.f('ix_articles_articles_category'), table_name='articles', schema='articles')
    op.drop_table('articles', schema='articles')

    op.execute(sa.schema.DropSchema('statistics', if_exists=True))
    op.execute(sa.schema.DropSchema('articles', if_exists=True))
    
    # ### end Alembic commands ###
